#!/usr/bin/perl

use perl5i::0;
use YAML::XS;
no utf8;  # its interfering with the DATA loading

my %Ignore_Emails = map { $_ => 1 } qw(
    unknown
    perlbug@perl.org
    perlbug-comment@perl.org
    perlbug-followup@perl.org
);

my $authors2email = Load(join "", <DATA>);
my $email2authors = invert_authors2email($authors2email);
1;

sub invert_authors2email {
    my $authors2email = shift;

    my %email2authors;
    for my $author ($authors2email->keys->flatten) {
        my $emails = $authors2email->{$author};

        for my $email (@$emails) {
            next if $Ignore_Emails{$email};

            say "$email is already owned by $email2authors{$email}"
              if $email2authors{$email};

            $email2authors{$email} = $author;
        }
    }

    return \%email2authors;
}

open my $log, "log.xml";
my @log = <$log>;
close $log;

open my $out, ">", "log.new.xml";
for my $line (@log) {
    if( $line =~ m{author="(.*?) &lt;(.*?)&gt;"} ) {
        my $author = $email2authors{$2};
        warn "Author for $line not found" unless $author;
        $line =~ s{author="(.*?)"}{author="$author"};
    }

    print $out $line;
}
close $out;


__DATA__
A. C. Yardley:
  - yardley@tanet.net
AUGUSTE-ETIENNE Jose:
  - jose.auguste-etienne@cgss-guyane.fr
Aaron B. Dossett:
  - aaron@iglou.com
Aaron Crane:
  - perl@aaroncrane.co.uk
Aaron J. Mackey:
  - ajm6q@virginia.edu
Aaron Kaplan:
  - unknown
Abe Timmerman:
  - abe@ztreet.demon.nl
Abhijit Menon-Sen:
  - ams@toroid.org
  - ams@wiw.org
Abigail:
  - abigail@abigail.be
  - abigail@fnx.com
Achim Bohnet:
  - ach@mpe.mpg.de
  - ach@rosat.mpe-garching.mpg.de
Adam Krolnik:
  - adamk@gypsy.cyrix.com
Adam Russell:
  - arussell@cs.uml.edu
Adam Spiers:
  - unknown
Adrian M. Enache:
  - enache@rdslink.ro
Adriano Ferreira:
  - a.r.ferreira@gmail.com
Akim Demaille:
  - akim@epita.fr
Alain Barbet:
  - alian@cpan.org
Alan Burlison:
  - Alan.Burlison@uk.sun.com
  - aburlison@cix.compulink.co.uk
Alan Champion:
  - achampio@lehman.com
Alan Ferrency:
  - alan@pair.com
Alan Grover:
  - awgrover@gmail.com
Alan Harder:
  - Alan.Harder@Ebay.Sun.COM
Albert Dvornik:
  - bert@genscan.com
Alessandro Forghieri:
  - alf@orion.it
Alex Davies:
  - adavies@ptc.com
  - alex.davies@talktalk.net
Alex Gough:
  - alex@rcon.org
Alex Vandiver:
  - alex@chmrr.net
  - alexmv@mit.edu
Alex Waugh:
  - alex@alexwaugh.com
Alexander Foken:
  - unknown
Alexander Gough:
  - alex-p5p@earth.li
Alexander Klimov:
  - ask@wisdom.weizmann.ac.il
Alexander Smishlajev:
  - als@turnhere.com
Alexander_Gernler@genua.de:
  - Alexander_Gernler@genua.de
Alexandr Ciornii:
  - alexchorny@gmail.com
  - alexchorny\100gmail.com
Alexey Mahotkin:
  - alexm@netli.com
Alexey Toptygin:
  - alexeyt@freeshell.org
Alexey Tourbin:
  - at@altlinux.ru
Alexey V. Barantsev:
  - barancev@kazbek.ispras.ru
Allen Smith:
  - allens@cpan.org
Eric Amick:
  - perlbug@perl.org
  - unknown
Anatoly Vorobey:
  - unknown
Anders Johnson:
  - ajohnson@nvidia.com
Andreas J König:
  - andk@cpan.org
  - andreas.koenig.7os6VVqR@franz.ak.mind.de
  - a.koenig@kulturbox.de
  - k@sissy.in-berlin.de
  - koenig@anna.mind.de
  - (none)
  - a.koenig@mind.de
  - k@anna.in-berlin.de
  - k@anna.mind.de
Andreas Karrer:
  - karrer@ife.ee.ethz.ch
Andreas Schwab:
  - schwab@LS5.informatik.uni-dortmund.de
  - schwab@issan.informatik.uni-dortmund.de
  - schwab@suse.de
Andrej Borsenkow:
  - Andrej.Borsenkow@mow.siemens.ru
Andrew:
  - unknown
Andrew Burt:
  - isis!aburt
Andrew Cohen:
  - cohen@andy.bu.edu
Andrew Hamm:
  - AHamm@civica.com.au
Andrew M. Langmead:
  - aml@world.std.com
Andrew Pimlott:
  - pimlott@abel.math.harvard.edu
  - pimlott@idiomtech.com
Andrew Rodland:
  - andrew@hbslabs.com
Andrew Savige:
  - ajsavige@yahoo.com.au
Andrey Sapozhnikov:
  - sapa@icb.chel.su
Andy Armstrong:
  - andy@hexten.net
Andy Bussey:
  - andybussey@yahoo.co.uk
Andy Dougherty:
  - doughera.lafayette.edu
  - doughera@fractal.phys.lafayette.edu
  - doughera@lafayette.edu
  - doughera@lafcol.lafayette.edu
  - doughera@newton.phys.lafayette.edu
Andy Lester:
  - andy@petdance.com
Andy Wardley:
  - unknown
Animator:
  - unknown
Anno Siegel:
  - anno4000@lublin.zrz.tu-berlin.de
Anton Berezin:
  - tobez@tobez.org
Anton Tagunov:
  - tagunov@motor.ru
Archer Sully:
  - archer@meer.net
Arjen Laarhoven:
  - arjen@nl.demon.net
Arnold D. Robbins:
  - arnold@emoryu2.arpa
  - gatech!skeeve!arnold
Art Green:
  - Art_Green@mercmarine.com
Art Haas:
  - ahaas@airmail.net
Artur Bergman:
  - arthur@contiller.se
  - sky@nanisky.com
Ash Berlin:
  - ash@cpan.org
Ask Bjoern Hansen:
  - ask@develooper.com
Audrey Tang:
  - cpan@audreyt.org
  - unknown
  - autrijus@ossf.iis.sinica.edu.tw
Axel Boldt:
  - unknown
Axel Kollmorgen:
  - unknown
Barrie Slaymaker:
  - barries@slaysys.com
Bas van Sisseren:
  - bas@quarantainenet.nl
Beckett Richard-qswi266:
  - unknown
Ben Carter:
  - bcarter@gumdrop.flyinganvil.org
Ben Morrow:
  - ben@morrow.me.uk
Ben Tilly:
  - ben_tilly@operamail.com
  - unknown
Benjamin Carter:
  - q.eibcartereio.=~m-b.{6}-cgimosx@gumdrop.flyinganvil.org
Benjamin Goldberg:
  - goldbb2@earthlink.net
Benjamin Holzman:
  - bah@ecnvantage.com
Benjamin Low:
  - b.d.low@unsw.edu.au
Benjamin Smith:
  - bsmith@cabbage.org.uk
Benjamin Stuhl:
  - sho_pi@hotmail.com
Benjamin Sugars:
  - bsugars@canoe.ca
Bernard Quatermass:
  - bernard@quatermass.co.uk
Bill Campbell:
  - bill@celestial.com
Bill Glicker:
  - billg@burrelles.com
Billy Constantine:
  - wdconsta@cs.adelaide.edu.au
Blair Zajac:
  - blair@orcaware.com
Bo Borgerson:
  - gigabo@gmail.com
Bo Lindbergh:
  - blgl@hagernas.com
Bob Dalgleish:
  - Robert.Dalgleish@sk.sympatico.ca
Bob Wilkinson:
  - perlbug@perl.org
Boris Zentner:
  - bzm@2bz.de
Boyd Gerber:
  - gerberb@zenez.com
Brooks D Boyd:
  - unknown
Brad Baxter:
  - unknown
Brad Gilbert:
  - b2gills@gmail.com
Brad Hughes:
  - brad@tgsmc.com
Brad Lanam:
  - bll@gentoo.com
Bram:
  - p5p@perl.wizbit.be
  - perl-rt@wizbit.be
  - perlbug-comment@perl.org
Brandon Black:
  - blblack@gmail.com
Brendan O'Dea:
  - bod@debian.org
Brent B. Powers:
  - powers@ml.com
Brent Dax:
  - brentdax@cpan.org
Brian Callaghan:
  - callagh@itginc.com
Brian Clarke:
  - clarke@appliedmeta.com
Brian Harrison:
  - brie@corp.home.net
Brian Ingerson:
  - ingy@ttul.org
Brian Jepson:
  - bjepson@oreilly.com
Brian McCauley:
  - nobull@mail.com
Bruce Barnett:
  - barnett@grymoire.crd.ge.com
Bruce P. Schuck:
  - bruce@aps.org
Byron Brummer:
  - byron@omix.com
Calle Dybedahl:
  - calle@lysator.liu.se
Campo Weijerman:
  - rfc822@nl.ibm.com
Carl Eklof:
  - CEklof@endeca.com
Cary D. Renzema:
  - caryr@mxim.com
Casey R. Tweten:
  - crt@kiski.net
  - perl@ctweten.amsite.com
Casey West:
  - casey@geeknest.com
Charles Bailey:
  - bailey.charles@gmail.com
  - bailey@HMIVAX.HUMGEN.UPENN.EDU
  - bailey@genetics.upenn.edu
  - bailey@hmivax.humgen.upenn.edu
  - bailey@newman.upenn.edu
Charles F. Randall:
  - crandall@free.click-n-call.com
Charles Lane:
  - lane@DUPHY4.Physics.Drexel.Edu
Charles Randall:
  - cfriv@yahoo.com
Chaskiel M Grundman:
  - unknown
Chia-liang Kao:
  - clkao@clkao.org
Chip Salzenberg:
  - chip@atlantic.net
  - chip@ci005.sv2.upperbeyond.com
  - chip@perl.com
  - chip@pobox.com
  - salzench@dun.nielsen.com
  - salzench@nielsenmedia.com
Chip Turner:
  - cturner@redhat.com
Chris 'BinGOs' Williams:
  - chris@bingosnet.co.uk
Chris Ball:
  - chris@cpan.org
Chris Bongaarts:
  - cab@tc.umn.edu
Chris Dolan:
  - chris@chrisdolan.net
Chris Faylor:
  - cgf@bbc.com
Chris Heath:
  - chris@heathens.co.nz
Chris Lightfoot:
  - chris@ex-parrot.com
Chris Nandor:
  - pudge@pobox.com
Chris Pepper:
  - unknown
Christian Burger:
  - burger@terra.mpikg-teltow.mpg.de
Christian Kirsch:
  - ck@held.mind.de
Christian Winter:
  - bitpoet@linux-config.de
Christoph Lamprecht:
  - ch.l.ngre@online.de
Christophe Grosjean:
  - christophe.grosjean@gmail.com
Christopher Davis:
  - ckd@loiosh.kei.com
Chuck D. Phillips:
  - cdp@hpescdp.fc.hp.com
Chuck Phillips:
  - perl@cadop.com
Chun Bing Ge:
  - gecb@cn.ibm.com
Claes Jakobsson:
  - claes@surfar.nu
Clinton A. Pierce:
  - clintp@geeksalad.org
  - cpierce1@ford.com
Clinton Gormley:
  - unknown
Colin Kuskie:
  - ckuskie@cadence.com
Colin McMillen:
  - mcmi0073@tc.umn.edu
Colin Meyer:
  - cmeyer@helvella.org
Colin Watson:
  - colinw@zeus.com
Conrad E. Kimball:
  - cek@tblv021.ca.boeing.com
Craig A. Berry:
  - craig.a.berry@gmail.com
  - craigberry@mac.com
  - Craig A. Berry)
DH:
  - crazyinsomniac@yahoo.com
Damian Conway:
  - damian@cs.monash.edu.au
Damon Atkins:
  - Damon.Atkins@nabaus.com.au
Dan Boorstein:
  - dan_boo@bellsouth.net
Dan Brook:
  - dbrook@easyspace.com
Dan Dascalescu:
  - bigbang7@gmail.com
Dan Faigin, Doug Landauer:
  - unknown@longtimeago
Dan Hale:
  - danhale@us.ibm.com
Dan Jacobson:
  - jidanni@hoffa.dreamhost.com
  - unknown
Dan Kogai:
  - dankogai@dan.co.jp
Dan Schmidt:
  - dfan@harmonixmusic.com
Dan Sugalski:
  - dan@sidhe.org
  - sugalsd@lbcc.cc.or.us
Daniel Berger:
  - djberg86@attbi.com
Daniel Chetlin:
  - daniel@chetlin.com
Daniel Frederick Crisman:
  - daniel@crisman.org
Daniel Grisinger:
  - dgris@dimensional.com
Daniel M. Quinlan:
  - unknown
Daniel Muiño:
  - dmuino@afip.gov.ar
Daniel P. Berrange:
  - dan@berrange.com
Daniel S. Lewart:
  - d-lewart@uiuc.edu
  - lewart@uiuc.edu
  - lewart@vadds.cvm.uiuc.edu
Daniel Yacob:
  - perl@geez.org
Danny Rathjens:
  - unknown
Danny Sadinoff:
  - sadinoff@olf.com
Darren/Torin/Who Ever:
  - torin@daft.com
Dave Bailey:
  - unknown
Dave Hartnoll:
  - Dave_Hartnoll@3b2.com
Dave Liney:
  - dave.liney@gbr.conoco.com
Dave Mitchell:
  - davem@fdisolutions.com
Dave Nelson:
  - David.Nelson@bellcow.com
Dave Paris:
  - unknown
Dave Rolsky:
  - autarch@urth.org
David Billinghurst:
  - David.Billinghurst@riotinto.com.au
David Cannings:
  - lists@edeca.net
David Cantrell:
  - david@cantrell.org.uk
David D. Kilzer:
  - ddkilzer@lubricants-oil.com
David Dick:
  - unknown
David Dyck:
  - david.dyck@fluke.com
  - dcd@tc.fluke.com
David E. Wheeler:
  - david@kineticode.com
  - david@wheeler.net
David Favor:
  - david@davidfavor.com
David Feldman:
  - david.feldman@tudor.com
David Glasser:
  - me@davidglasser.net
David Golden:
  - dagolden@cpan.org
  - xdaveg@gmail.com
David H. Adler:
  - dha@panix.com
David Hammen:
  - hammen@gothamcity.jsc.nasa.gov
David J. Fiander:
  - davidf@mks.com
David Kerry:
  - davidk@tor.securecomputing.com
David Landgren:
  - david@landgren.net
David Leadbeater:
  - dgl@dgl.cx
David M. Syzdek:
  - david@syzdek.net
David Manura:
  - dm.list@math2.org
David McLean:
  - davem@icc.gsfc.nasa.gov
David Mitchell:
  - davem@iabyn.com
David Muir Sharnoff:
  - muir@idiom.com
David Nicol:
  - davidnicol@gmail.com
  - whatever@davidnicol.com
David R. Favor:
  - dfavor@austin.ibm.com
David Sparks:
  - daves@ca.sophos.com
Davin Milun:
  - milun@cs.Buffalo.EDU
Dean Roehrich:
  - roehrich@cray.com
Dennis Kaarsemaker:
  - dennis@camel.ams6.corp.booking.com
Dennis Marsa:
  - dennism@cyrix.com
Devin Heitmueller:
  - devin.heitmueller@gmail.com
Diab Jerius:
  - dj@head-cfa.harvard.edu
Tom Dinger:
  - unknown
Dmitry Karasik:
  - dk@tetsuo.karasik.eu.org
Dominic Dunlop:
  - domo@computer.org
  - domo@slipper.ip.lu
  - domo@tcp.ip.lu
Dominique Quatravaux:
  - unknown
Dorner Thomas:
  - tdorner@amadeus.net
Doug MacEachern:
  - dougm@covalent.net
  - dougm@opengroup.org
  - dougm@osf.org
Doug Wilson:
  - Doug_Wilson@intuit.com
Douglas Lankshear:
  - doug@lankshear.net
Dr.Ruud:
  - rvtol+news@isolution.nl
Drago Goricanec:
  - drago@raptor.otsd.ts.fujitsu.co.jp
Duke Leto:
  - jonathan@leto.net
Duncan Findlay:
  - duncf@debian.org
Earl Hood:
  - unknown
Ed Allen Smith:
  - easmith@beatrice.rutgers.edu
Ed Peschko:
  - epeschko@den-mdev1
Ed Santiago:
  - esm@pobox.com
Edgar Bering:
  - trizor@gmail.com
Edmund Bacon:
  - unknown
Edward Avis:
  - ed@membled.com
Edward Moy:
  - emoy@apple.com
Edward Peschko:
  - edwardp@excitehome.net
  - esp5@pge.com
Elaine -HFB- Ashton:
  - elaine@chaos.wustl.edu
Elizabeth Mattijsen:
  - liz@dijkmat.nl
Enrico Sorcinelli:
  - bepi@perl.it
  - enrico.sorcinelli@gmail.com
Eric Amick:
  - unknown
Eric Bartley:
  - bartley@icd.cc.purdue.edu
Eric Brine:
  - ikegami@adaelis.com
Eric E. Coe:
  - Eric.Coe@oracle.com
Eric Fifer:
  - egf7@columbia.edu
Eric Melville:
  - perlbug@perl.org
Eric Promislow:
  - ericp@ActiveState.com
Fabien TASSIN:
  - tassin@eerie.fr
Father Chrysostomos:
  - perlbug-followup@perl.org
  - sprout@cpan.org
Fergal Daly:
  - fergal@esatclear.ie
Fifer, Eric:
  - EFifer@sanwaint.com
Florian Ragwitz:
  - rafl@debian.org
Frank Ridderbusch:
  - Frank.Ridderbusch@pdb.siemens.de
Frank Tobin:
  - ftobin@uiuc.edu
Frank Wiegand:
  - frank.wiegand@gmail.com
François Désarménien:
  - desar@club-internet.fr
Fyodor Krasnov:
  - fyodor@aha.ru
G. Del Merritt:
  - del@intranetics.com
Gabor Szabo:
  - szabgab@gmail.com
Garry T. Williams:
  - garry@zvolve.com
Gary Clark:
  - GaryC@mail.jeld-wen.com
Gary L. Armstrong:
  - unknown
Gene Sullivan:
  - perlbug-followup@perl.org
Geoffrey F. Green:
  - geoff-public@stuebegreen.com
Geoffrey T. Dairiki:
  - dairiki at dairiki.org
Georg Schwarz:
  - geos@epost.de
George Greer:
  - greerga@m-l.org
  - perl@greerga.m-l.org
George Necula:
  - necula@eecs.berkeley.edu
Geraint A Edwards:
  - gedge@serf.org
Gerard Goossen:
  - gerard@ggoossen.net
  - gerard@tty.nl
Gerben Wierda:
  - G.C.Th.Wierda@AWT.nl
Gerd Knops:
  - gerti@BITart.com
Gerrit P. Haase:
  - gp@familiehaase.de
Giles Lean:
  - giles@nemeton.com.au
Giroux, Mike (Exchange):
  - mgiroux@bear.com
Gisle Aas:
  - aas@aas.no
  - aas@bergen.sn.no
  - gisle@aas.no
  - gisle@activestate.com
Glenn Linderman:
  - perl@nevcal.com
Goro Fuji:
  - g.psy.va@gmail.com
  - gfuji@cpan.org
  - unknown
Graham Barr:
  - Graham.Barr@tiuk.ti.com
  - bodg@tiuk.ti.com
  - gbarr@pobox.com
  - gbarr@ti.com
  - gbarr@monty.mutatus.co.uk
Graham TerMarsch:
  - graham@howlingfrog.com
Paul Green:
  - Paul.Green@stratus.com
  - pgreen@seussnt.stratus.com
Greg Bacon:
  - gbacon@adtrn-srv4.adtran.com
Greg Chapman:
  - glc@well.com
Greg Matheson:
  - lang@ms.chinmin.edu.tw
Greg Seibert:
  - seibert@Lynx.COM
Greg Ward:
  - greg@bic.mni.mcgill.ca
Gurusamy Sarathy:
  - gsar@cpan.org
  - gsar@engin.umich.edu
Guy Decoux:
  - decoux@moulon.inra.fr
Gwyn Judd:
  - b.judd@xtra.co.nz
H.Merijn Brand:
  - merijn@a5.(none)
  - merijn@l1.procura.nl
  - "[mailto:h.m.brand@xs4all.nl]"
  - h.m.brand@xs4all.nl
Hal Morris:
  - hom00@utsglobal.com
Hallvard B Furuseth:
  - h.b.furuseth@usit.uio.no
Hans Dieter Pearcey:
  - hdp@pobox.com
Hans Ginzel:
  - hans@kolej.mff.cuni.cz
Hans Mulder:
  - hans@icgned.nl
  - hansm@euronet.nl
  - hansm@icgned.nl
  - hansmu@xs4all.nl
Hans Ranke:
  - Hans.Ranke@ei.tum.de
Harmen:
  - harm@dds.nl
Harri Pasanen:
  - harri.pasanen@trema.com
Helmut Jarausch:
  - jarausch@numa1.igpm.rwth-aachen.de
Henrik Tougaard:
  - ht.000@foa.dk
Hernan Perez Masci:
  - hmasci@uolsinectis.com.ar
Horst von Brand:
  - vonbrand@sleipnir.valparaiso.cl
Hrunting Johnson:
  - unknown
Hubert Feyrer:
  - hubert.feyrer@informatik.fh-regensburg.de
Hugo van der Sanden:
  - hv@crypt.compulink.co.uk
  - hv@crypt.org
  - hv@iii.co.uk
Hunter Kelly:
  - retnuh@zule.pixar.com
Iain "Spoon" Truskett:
  - perl@dellah.anu.edu.au
  - unknown
  - spoon@cpan.org
  - spoon@dellah.org
Ian Goodacre:
  - Ian.Goodacre@xtra.co.nz
  - perlbug-followup@perl.org
Ian Phillipps:
  - Ian.Phillipps@iname.com
Igor Sutton:
  - IZUT@cpan.org
Ilmari Karonen:
  - iltzu@sci.fi
Ilya Martynov:
  - ilya@martynov.org
  - perlbug@perl.org
Ilya N. Golubev:
  - gin@mo.msk.ru
Ilya Sandler:
  - Ilya.Sandler@etak.com
Ilya Zakharevich:
  - ilya@math.berkeley.edu
  - ilya@math.ohio-state.edu
Inaba Hiroto:
  - inaba@st.rim.or.jp
Indy Singh:
  - indy@nusphere.com
Information Service:
  - info@lingo.kiev.ua
Ingo Weinhold:
  - ingo_weinhold@gmx.de
  - unknown
Irving Reid:
  - irving@tor.securecomputing.com
Ivan Tubert-Brohman:
  - itub@cpan.org
J. David Blackstone:
  - jdb@dfwnet.sbms.sbc.com
J. van Krieken:
  - John.van.Krieken@ATComputing.nl
JD Laub:
  - jdl@access-health.com
James:
  - james@rf.net
James A. Duncan:
  - jduncan@fotango.com
James Bence:
  - unknown
James FitzGibbon:
  - james@ican.net
James Jurach:
  - muaddib@erf.net
James Mastros:
  - james@mastros.biz
  - theorb@desert-island.me.uk
Jan D:
  - jan.djarv@mbox200.swipnet.se
Jan Dubois:
  - jan.dubois@ibm.net
  - jand@activestate.com
Jan Starzynski:
  - jan@planet.de
Jan-Pieter Cornet:
  - johnpc@xs4all.nl
Jari Aalto:
  - jari.aalto@poboxes.com
Jarkko Hietaniemi:
  - Jarkko.Hietaniemi@cc.hut.fi
  - jhi@alpha.hut.fi
  - jhi@cc.hut.fi
  - jhi@hut.fi
  - jhi@iki.fi
Jason A. Smith:
  - smithj4@rpi.edu
Jason E. Stewart:
  - jason@openinformatics.com
Jason Vas Dias:
  - unknown
Jay Hannah:
  - jay@jays.net
  - jhannah@omnihotels.com
Jay Rogers:
  - jay@rgrs.com
Jeff McDougal:
  - jmcdo@cris.com
Jeff Okamoto:
  - okamoto@corp.hp.com
  - okamoto@hpcc123.corp.hp.com
Jeff Pinyan:
  - japhy@pobox.com
Jeff Siegal:
  - jbs@eddie.mit.edu
Jeffrey Friedl:
  - jfriedl@regex.info
Jens Hamisch:
  - jens@Strawberry.COM
Jens T. Berger Thielemann:
  - jensthi@ifi.uio.no
Jens Thomsen:
  - jens@fiend.cis.com
Jens-Uwe Mager:
  - jum@helios.de
Jeremy D. Zawodny:
  - jzawodn@wcnet.org
  - Jeremy@Zawodny.com
Jeremy H. Brown:
  - jhbrown@ai.mit.edu
Jeremy Madea:
  - jmadea@inktomi.com
Jerrad Pierce:
  - belg4mit@MIT.EDU
Jerry D. Hedden:
  - jdhedden@cpan.org
  - jdhedden@yahoo.com
  - jhedden@PN100-02-2-356p.corp.bloomberg.com
Jesse:
  - unknown
Jesse Glick:
  - jesse@ginger
Jesse Vincent:
  - jesse@bestpractical.com
  - jesse@fsck.com
Jesús Quiroga:
  - jquiroga@pobox.com
Jim Avera:
  - avera@hal.com
Jim Cromie:
  - jcromie@cpan.org
  - jim.cromie@gmail.com
Jim Meyering:
  - meyering@asic.sc.ti.com
Jim Schneider:
  - jschneid@netilla.com
Jochen Wiedmann:
  - joe@ispsoft.de
Jody Belka:
  - lists-p5p@pimb.org
Joe Buehler:
  - jbuehler@hekimian.com
Joe McMahon:
  - mcmahon@ibiblio.org
Joe Orton:
  - jorton@redhat.com
Joe Schaefer:
  - joe+perl@sunstarsys.com
Joe Smith:
  - jsmith@inwap.com
Johan Vromans:
  - JVromans@squirrel.nl
  - jvromans@squirrel.nl
Johann Klasek:
  - jk@auto.tuwien.ac.at
John Bley:
  - jbb6@acpub.duke.edu
John Borwick:
  - jhborwic@unity.ncsu.edu
John Cerney:
  - j-cerney1@ti.com
John D Groenveld:
  - groenvel@cse.psu.edu
John E. Malmberg:
  - wb8tyw@qsl.net
  - wb8tyw@gmail.com
John Holdsworth:
  - coldwave@bigfoot.com
John Hughes:
  - john@AtlanTech.COM
  - john@titanic.atlantech.com
John Kristian:
  - jmk2001@engineer.com
John L. Allen:
  - allen@gateway.grumman.com
  - allen@grumman.com
John Macdonald:
  - jmm@revenge.elegant.com
John Nolan:
  - jpnolan@Op.Net
John P. Linderman:
  - jpl@research.att.com
John Peacock:
  - john.peacock@havurah-software.org
  - jpeacock@havurah-software.org
  - jpeacock@jpeacock-hp.doesntexist.org
  - jpeacock@rowman.com
  - bug-Module-CoreList@rt.cpan.org
  - jpeacock@dsl092-147-156.wdc1.dsl.speakeasy.net
John Q. Linux:
  - jql@accessone.com
  - jql@jql.accessone.com
John Redford:
  - jmr@whirlwind.fmr.com
John Stoffel:
  - jfs@fluent.com
John Stumbles:
  - jstumbles@bluearc.com
John Tobey:
  - jtobey@john-edwin-tobey.org
  - jtobey@user1.channel1.com
John W. Krahn:
  - unknown
John Wright:
  - john.wright@hp.com
  - john@johnwright.org
Jon Eveland:
  - jweveland@yahoo.com
Jon Gunnip:
  - jongunnip@hotmail.com
Jon Orwant:
  - orwant@media.mit.edu
Jonathan Biggar:
  - jon@sems.com
Jonathan D Johnston:
  - jdjohnston2@juno.com
Jonathan Fine:
  - jfine@borders.com
Jonathan Hudson:
  - Jonathan.Hudson@jrhudson.demon.co.uk
Jonathan I. Kamens:
  - jik@kamens.brookline.ma.us
Jonathan Roy:
  - roy@idle.com
Jonathan Steinert:
  - unknown
Jonathan Stowe:
  - gellyfish@gellyfish.com
Joost van Baal:
  - J.E.vanBaal@uvt.nl
Jos Boumans:
  - kane@xs4all.net
Jos I. Boumans:
  - jos@dwim.org
  - kane@cpan.org
  - kane@dwim.org
Jose Auguste-Etienne:
  - Jose.auguste-etienne@cgss-guyane.fr
Joseph N. Hall:
  - joseph@5sigma.com
Joseph S. Myers:
  - jsm28@cam.ac.uk
  - jsm28@hermes.cam.ac.uk
Joshua ben Jore:
  - jjore@cpan.org
Joshua E. Rodd:
  - jrodd@pbs.org
Joshua Juran:
  - jjuran@gmail.com
Joshua Pritikin:
  - joshua.pritikin@db.com
Joshua Rodd:
  - joshua@rodd.us
José Pedro Oliveira:
  - jpo@di.uminho.pt
Juerd:
  - juerd@convolution.nl
  - juerd@cpan.org
  - "#####@juerd.nl"
Juha Laiho:
  - juha.laiho@Elma.Net
KAWAI Takanori:
  - GCD00051@nifty.ne.jp
Karl:
  - khw@karl.(none)
Karl Heuer:
  - kwzh@gnu.org
Karl Williamson:
  - khw@khw-desktop.(none)
Karsten Sperling:
  - spiff@phreax.net
Kay Röpke:
  - kay@dolphin-services.de
  - kroepke@dolphin-services.de
Keith Neufeld:
  - neufeld@fast.pvi.org
Ken Fox:
  - kfox@ford.com
Ken Hirsch:
  - kenhirsch@ftml.net
Ken Neighbors:
  - perlbug@perl.org
Ken Shan:
  - ken@digitas.harvard.edu
Ken Williams:
  - ken.williams@thomsonreuters.com
  - ken@mathforum.org
Kenichi Ishigaki:
  - ishigaki@cpan.org
Kenneth Albanowski:
  - kjahds@kjahds.com
Kenneth Duda:
  - kjd@cisco.com
Kevin Chase:
  - kevincha99@hotmail.com
Kevin Ruscoe:
  - Kevin.Ruscoe@ubsw.com
Kevin Ryde:
  - perlbug-followup@perl.org
  - unknown
Kingpin:
  - mthurn@copper.dulles.tasc.com
Kirrily Robert:
  - skud@infotrope.net
Kragen Sitaker:
  - kragen@pobox.com
Krishna Sethuraman:
  - krishna@sgi.com
Kriton Kyrimis:
  - kyrimis@princeton.edu
Kurt D. Starsinic:
  - kstar@wolfetech.com
  - kstar@www.chapin.edu
  - kstar@cpan.org
LAUN Wolfgang:
  - wolfgang.laun@alcatel.at
Lanning, Scott:
  - lannings@who.int
Larry Parmelee:
  - parmelee@CS.Cornell.EDU
Larry Shatzer:
  - fugazi@zyx.net
Larry Shatzer Jr.:
  - larrysh@cpan.org
  - lshatzer@islanddata.com
Larry W. Virden:
  - lvirden@cas.org
Larry Wall:
  - larry@netlabs.com
  - larry@wall.org
  - lwall@jpl-devvax.jpl.nasa.gov
  - lwall@netlabs.com
  - lwall@scalpel.netlabs.com
  - lwall@sems.com
Laszlo Molnar:
  - laszlo.molnar@eth.ericsson.se
Leif Huhn:
  - leif@hale.dkstat.com
Len Johnson:
  - lenjay@ibm.net
Len Weisberg:
  - unknown
Leon Brocard:
  - acme@astray.com
Les Peters:
  - lpeters@aol.net
Lincoln Stein:
  - lstein@formaggio.cshl.org
  - lstein@genome.wi.mit.edu
Linda Walsh:
  - unknown
Lionel Cons:
  - lionel.cons@cern.ch
Lubomir Rintel:
  - lkundrak@v3.sk
Luc St-Louis:
  - luc.st-louis@ca.transport.bombardier.com
Lucas Holt:
  - unknown
Lukas Mai:
  - unknown
Luke Closs:
  - lukec@cpan.org
Luke Ross:
  - lukeross@gmail.com
Lupe Christoph:
  - lupe@alanya.m.isar.de
  - lupe@lupe-christoph.de
Luther Huffman:
  - lutherh@infinet.com
M.J.T. Guy:
  - mjtg@cus.cam.ac.uk
  - mjtg@cam.ac.uk
Major Sébastien:
  - sebastien.major@crdp.ac-caen.fr
Makoto MATSUSHITA:
  - matusita@ics.es.osaka-u.ac.jp
Malcolm Beattie:
  - mbeattie@sable.ox.ac.uk
Mandalemula, Rajesh:
  - Rajesh.Mandalemula@deshaw.com
Manuel Valente:
  - mvalente@idealx.com
Marc Lehmann:
  - pcg@goof.com
Marcel Grünauer:
  - marcel@codewerk.com
Marcus Holland-Moritz:
  - mhx-perl@gmx.net
  - mhx@r2d2.(none)
Marek Rouchal:
  - marek.rouchal@infineon.com
Mark A. Hershberger:
  - mah@everybody.org
Mark Biggar:
  - markb@rdcf.sm.unisys.com
Mark Bixby:
  - mark@bixby.org
Mark Dickinson:
  - dickins3@fas.harvard.edu
Mark Fisher:
  - fisherm@tce.com
Mark Fowler:
  - mark@twoshortplanks.com
Mark J. Reed:
  - mreed@strange.turner.com
Mark-Jason Dominus:
  - mjd@plover.com
Mark Kettenis:
  - kettenis@wins.uva.nl
Mark Kvale:
  - kvale@phy.ucsf.edu
Mark Leighton Fisher:
  - mark-fisher@mindspring.com
Mark Mielke:
  - mark@mark.mielke.cc
Mark Overmeer:
  - mark@overmeer.net
Mark P Lutz:
  - tecmpl1@triton.ca.boeing.com
Mark Pease:
  - peasem@primenet.com
Mark Pizzolato:
  - mark@infocomm.com
Mark Stosberg:
  - mark@summersault.com
Marko Asplund:
  - aspa@merlot.kronodoc.fi
Marnix (ain't unix!) A. van Ammers:
  - pttesac!marnix!vanam
Martien Verbruggen:
  - mgjv@comdyn.com.au
Martijn Koster:
  - mak@excitecorp.com
Martin Becker:
  - unknown
Martin Hasch:
  - mhasch@cpan.org
Martin Husemann:
  - martin@duskware.de
Martin J. Bligh:
  - mbligh@us.ibm.com
Martin Lichtin:
  - lichtin@bivio.com
Martin Pool:
  - mbp@samba.org
Martti Rahkila:
  - martti.rahkila@hut.fi
Marty Lucich:
  - marty@netcom.com
Marty Pauley:
  - marty+p5p@kasei.com
Martyn Pearce:
  - martyn@inpharmatica.co.uk
Marvin Humphrey:
  - marvin@rectangular.com
Masahiro KAJIURA:
  - masahiro.kajiura@toshiba.co.jp
Mashrab Kuvatov:
  - kmashrab@uni-bremen.de
Mathias Koerber:
  - mathias@dnssec1.singnet.com.sg
Mathieu Arnold:
  - m@absolight.fr
Matt Kraai:
  - kraai@ftbfs.org
Matt S Trout:
  - mst@shadowcat.co.uk
Matt Sergeant:
  - matt@sergeant.org
Matt Taggart:
  - taggart@debian.org
Matthew Sachs:
  - matthewg@zevils.com
Matthew T Harden:
  - mthard@mthard1.monsanto.com
Matthias Ulrich Neeracher:
  - neeri@iis.ee.ethz.ch
  - neeracher@mac.com
Matthias Urlichs:
  - smurf@noris.net
Matthijs van Duin:
  - xmath@cpan.org
Mattia Barbon:
  - mbarbon@dsi.unive.it
Maurizio Loreti:
  - maurizio.loreti@pd.infn.it
Max Baker:
  - max@warped.org
Max Maischein:
  - corion@corion.net
Merijn Broeren:
  - merijnb@iloquent.nl
Michael A Chase:
  - mchase@ix.netcom.com
Michael Breen:
  - perl@mbreen.com
Michael Carman:
  - mjcarman@home.com
Michael Cartmell:
  - unknown
Michael Cummings:
  - mcummings@gentoo.org
Michael De La Rue:
  - mikedlr@it.com.pl
  - mikedlr@tardis.ed.ac.uk
Michael G. Schwern:
  - schwern@pobox.com
Michael King:
  - mike808@users.sourceforge.net
Michael Mahan:
  - mahanm@nextwork.rose-hulman.edu
Michael Schroeder:
  - Michael.Schroeder@informatik.uni-erlangen.de
Michael Somos:
  - somos@grail.cba.csuohio.edu
Michael Stevens:
  - mstevens@etla.org
Michael Witten:
  - mfwitten@gmail.com
Mik Firestone:
  - fireston@lexmark.com
Mike Giroux:
  - rmgiroux@acm.org
Mike Hopkirk (hops):
  - hops@scoot.pdev.sco.com
  - hops@sco.com
Mike Mestnik:
  - MMestnik@rustconsulting.com
Mike Pomraning:
  - mjp@pilcrow.madison.wi.us
Mike Schilli:
  - m@perlmeister.com
Mike Stok:
  - mike@stok.co.uk
Mike W Ellwood:
  - mwe@rl.ac.uk
Mikhail Zabaluev:
  - mhz@alt-linux.org
Milosz Tanski:
  - mtanski@gridapp.com
Milton Hankins {64892}:
  - webtools@uewrhp03.msd.ray.com
Milton L. Hankins:
  - mlh@swl.msd.ray.com
Molnar Laszlo:
  - molnarl@cdata.tvnet.hu
Moritz Lenz:
  - Moritz Lenz
  - moritz@casella.verplant.org
  - moritz@faui2k3.org
Mr. Nobody:
  - mrnobo1024@yahoo.com
Murray Nesbitt:
  - murray@nesbitt.ca
Nat Torkington:
  - gnat@frii.com
  - gnat@prometheus.frii.com
Nathan Kurz:
  - nate@valleytel.net
Neale Ferguson:
  - neale@VMA.TABNSW.COM.AU
Neil Bowers:
  - neilb@cre.canon.co.uk
Neil Watkiss:
  - neil.watkiss@sophos.com
Nicholas Clark:
  - Nicholas Clark (sans From field in mail header)
  - nick@ccl4.org
Nicholas Oxhøj:
  - unknown
Nick Ing-Simmons:
  - Nick.Ing-Simmons@tiuk.ti.com
  - nick@ni-s.u-net.com
  - nik@tiuk.ti.com
Nick Williams:
  - Nick.Williams@morganstanley.com
Nigel Sandever:
  - njsandever@hotmail.com
Niklas Edmundsson:
  - unknown
Niko Tyni:
  - ntyni@debian.org
Nikola Knezevic:
  - indy@tesla.rcub.bg.ac.yu
Nikola Milutinovic:
  - unknown
Nikolai Eipel:
  - eipel@web.de
Noah:
  - sitz@onastick.net
Norbert Pueschel:
  - pueschel@imsdd.meb.uni-bonn.de
Norton Allen:
  - allen@huarp.harvard.edu
  - nort@bottesini.harvard.edu
  - nort@qnx.com
OKAIE Yutaka:
  - unknown
Offer Kaye:
  - offer.kaye@gmail.com
Olaf Flebbe:
  - o.flebbe@science-computing.de
Olivier Thauvin:
  - olivier.thauvin@aerov.jussieu.fr
Olli Savia:
  - unknown
Ollivier Robert:
  - roberto@eurocontrol.fr
  - roberto@keltia.freenix.fr
Orton, Yves:
  - yves.orton@de.mci.com
Osvaldo Villalon:
  - ovillalon@dextratech.com
Ovid:
  - publiustemp-p5p3@yahoo.com
  - publiustemp-p5p@yahoo.com
  - cp@onsitetech.com
Owen Taylor:
  - owt1@cornell.edu
Patrick Dugnolle:
  - patrick.dugnolle@bnpparibas.com
Patrick Hayes:
  - Patrick.Hayes.CAP_SESA@renault.fr
Patrick O'Brien:
  - pdo@cs.umd.edu
Paul David Fardy:
  - pdf@morgan.ucs.mun.ca
Paul Eggert:
  - eggert@sea.sm.unisys.com
  - eggert@twinsun.com
Paul Fenwick:
  - pjf@perltraining.com.au
Paul Gaborit:
  - Paul.Gaborit@enstimac.fr
Paul Green:
  - Paul.Green@stratus.com
Paul Holser:
  - Paul.Holser.pholser@nortelnetworks.com
Paul Johnson:
  - paul@pjcj.net
Paul Lindner:
  - lindner@inuus.com
Paul Marquess:
  - Paul.Marquess@btinternet.com
  - Paul.Marquess@ntlworld.com
  - paul.marquess@btinternet.com
  - pmarquess@bfsec.bt.co.uk
  - pmqs@cpan.org
Paul Moore:
  - Paul.Moore@uk.origin-it.com
Paul Saab:
  - ps@yahoo-inc.com
Paul Schinder:
  - schinder@pobox.com
Paul Szabo:
  - psz@maths.usyd.edu.au
Paul de Weerd:
  - unknown
Per Einar Ellefsen:
  - per.einar@skynet.be
Perl 5 Porters:
  - perl5-porters.nicoh.com
  - perl5-porters@africa.nicoh.com
Peter BARABAS:
  - perlbug@perl.org
Peter Chines:
  - pchines@nhgri.nih.gov
Peter Dintelmann:
  - Peter.Dintelmann@Dresdner-Bank.com
  - Peter.Dintelmann@dresdner-bank.com 
Peter E. Yee:
  - yee@trident.arc.nasa.gov
Peter J. Farley III:
  - pjfarley@banet.net
Peter O'Gorman:
  - peter@pogma.com
Peter Prymmer:
  - PPrymmer@factset.com
  - pvhp@forte.com
  - pvhp@best.com
Peter Scott:
  - Peter@PSDT.com
Peter Wolfe:
  - wolfe@teloseng.com
Peter van Heusden:
  - pvh@junior.uwc.ac.za
Petter Reinholdtsen:
  - pere@hungry.com
Phil Lobbes:
  - phil@perkpartners.com
Philip Hazel:
  - perlbug-followup@perl.org
Philip M. Gollucci:
  - pgollucci@p6m7g8.com
Philip Newton:
  - Philip.Newton@datenrevision.de
  - pne@cpan.org
Philippe Bruhat (BooK):
  - book@cpan.org
Philippe M. Chiasson:
  - gozer@ActiveState.com
Piers Cawley:
  - pdcawley@bofh.org.uk
Piotr Fusik:
  - pfusik@op.pl
Piotr Klaban:
  - makler@oryl.man.torun.pl
Pixel:
  - pixel@mandrakesoft.com
Pradeep Hodigere:
  - phodigere@yahoo.com
Radu Greab:
  - radu@netsoft.ro
Rafael Garcia-Suarez:
  - rgarciasuarez@gmail.com
  - rgs@consttype.org
Rainer Orth:
  - ro@TechFak.Uni-Bielefeld.DE
Rainer Tammer:
  - tammer@tammer.net
Rajesh Vaidheeswarran:
  - rv@gnu.org
Ralf S. Engelschall:
  - rse@engelschall.com
Randal L. Schwartz:
  - merlyn@stonehenge.com
  - merlyn@gadget.cscaper.com
  - perlbug@perl.org
Randall Gellens:
  - randy@qualcomm.com
Randolf Werner:
  - randolf.werner@sap.com
Randy J Ray:
  - rjray@uswest.com
  - rjray@redhat.com
Randy W. Sims:
  - ml-perl@thepierianspring.org
  - perlbug@perl.org
Raphael Manfredi:
  - Raphael.Manfredi@pobox.com
  - Raphael_Manfredi@grenoble.hp.com
Raul Dias:
  - raul@dias.com.br
Raymund Will:
  - ray@caldera.de
Redvers Davies:
  - red@criticalintegration.com
Reini Urban:
  - rurban@x-ray.at
Renée Bäcker:
  - reneeb@reneeb-desktop.(none)
  - unknown
  - renee.baecker@smart-websolutions.de
Ricardo SIGNES:
  - rjbs@cpan.org
Rich Morin:
  - rdm@cfcl.com
Rich Rauenzahn:
  - rrauenza@hp.com
Richard A. Wells:
  - Rwells@uhs.harvard.edu
Richard Clamp:
  - richardc@unixbeard.net
Richard Foley:
  - Richard.Foley@rfi.net
  - richard.foley@rfi.net
Richard Hitt:
  - rbh00@utsglobal.com
Richard Kandarian:
  - richard.kandarian@lanl.gov
Richard L. Maus:
  - rmaus@monmouth.com
Richard Soderberg:
  - p5-authors@crystalflame.net
Rick Delaney:
  - rick@consumercontact.com
Risto Kankkunen:
  - unknown
Rob Napier:
  - rnapier@employees.org
Robert May:
  - robertmay@cpan.org
Robert Millan:
  - rmh@debian.org
Robert Sebastian Gerus:
  - arachnist@gmail.com
Robert Spier:
  - rspier@pobox.com
Roberto C. Sänchez:
  - roberto@connexer.com
Robin Barker:
  - RMBarker@cpan.org
  - Robin.Barker@npl.co.uk
  - rmb1@cise.npl.co.uk
  - rmb@cise.npl.co.uk
Robin Houston:
  - robin@cpan.org
Roca Carrio, Ignasi (PO EP):
  - Ignasi.Roca@fujitsu-siemens.com
Roca, Ignasi:
  - ignasi.roca@fujitsu.siemens.es
Rocco Caputo:
  - troc@netrus.net
Roderick Schertler:
  - roderick@argon.org
  - roderick@gate.net
  - roderick@ibcinc.com
Ronald F. Guilmette:
  - rfg@monkeys.com
Ronald J. Kimball:
  - rjk@linguist.dartmouth.edu
RonaldWS@aol.com:
  - RonaldWS@aol.com
Ruben Schattevoy:
  - schattev@imb-jena.de
Rudolph Todd Maceyko:
  - rm55+@pitt.edu
Rujith S. de Silva:
  - desilva@netbox.com
Russ Allbery:
  - rra@stanford.edu
Russell Mosemann:
  - mose@ccsn.edu
SADAHIRO Tomoyuki:
  - BQW10602@nifty.com
  - SADAHIRO@cpan.org
SAKAI Kiyotaka:
  - ksakai@netwk.ntt-at.co.jp
Salvador Fandiño:
  - unknown
  - sfandino@yahoo.com
Salvador Ortiz Garcia:
  - sog@msg.com.mx
Sam Tregar:
  - sam@tregar.com
Sam Vilain:
  - sam@vilain.net
Sascha Blank:
  - unknown
Schuyler Erle:
  - schuyler@oreilly.com
Scott Bronson:
  - bronson@rinspin.com
Scott Gifford:
  - sgifford@tir.com
Scott Henry:
  - scotth@sgi.com
Scott L. Miller:
  - Scott.L.Miller@Compaq.com
Sean Dague:
  - sean@dague.net
Sean Davis:
  - dive@ender.com
Sean M. Burke:
  - sburke@cpan.org
Sean Robinson:
  - robinson_s@sc.maricopa.edu
Sean Sheedy:
  - seans@ncube.com
Sebastian Steinlechner:
  - steinlechner@gmx.net
Sergey Skvortsov:
  - unknown
Shawn:
  - svicalifornia@gmail.com
Shawn Boyette:
  - unknown
Sherm Pendley:
  - sherm@dot-app.org
Shigeya Suzuki:
  - shigeya@foretune.co.jp
Shinya Hayakawa:
  - hayakawa@livedoor.jp
Shishir Gundavaram:
  - shishir@ruby.ora.com
Shlomi Fish:
  - shlomif@iglu.org.il
  - shlomif@vipe.technion.ac.il
Simon 'corecode' Schubert:
  - corecode@fs.ei.tum.de
Simon Cozens:
  - simon@netthink.co.uk
Simon Glover:
  - scog@roe.ac.uk
Sisyphus:
  - sisyphus1@optusnet.com.au
Slaven Rezic:
  - eserte@cs.tu-berlin.de
  - slaven@rezic.de
  - srezic@iconmobile.com
  - bug-Storable@rt.cpan.org
  - Srezic@Iconmobile.Com
  - srezic@cpan.org
Smylers:
  - Smylers@stripey.com
Solar Designer:
  - solar@openwall.com
Spider Boardman:
  - spider@Orb.Nashua.NH.US
  - spider@orb.nashua.nh.us
  - spider@web.zk3.dec.com
  - Spider.Boardman@Orb.Nashua.NH.US
  - spidb@cpan.org
Spiros Denaxas:
  - spiros@lokku.com
Sreeji K Das:
  - sreeji_k@yahoo.com
Starsinic, Kurt:
  - Kurt_Starsinic@ml.com
Stas Bekman:
  - stas@stason.org
Steffen Müller:
  - smueller@cpan.org
  - unknown
  - wyp3rlx02@sneakemail.com
  - 0mgwtfbbq@sneakemail.com
Steffen Ullrich:
  - coyote.frank@gmx.net
Stepan Kasal:
  - skasal@redhat.com
Stephane Payrard:
  - properler@freesurf.fr
  - stef@francenet.fr
Stephanie Beals:
  - bealzy@us.ibm.com
Stephen Clouse:
  - stephenc@theiqgroup.com
Stephen McCamant:
  - alias@mcs.com
  - smcc@mit.edu
Stephen O. Lidie:
  - lusol@turkey.cc.Lehigh.EDU
Stephen P. Potter:
  - spp@ds.net
  - spp@psa.pencom.com
  - spp@psasolar.colltech.com
Stephen Zander:
  - gibreel@pobox.com
  - srz@loopback
  - stephen.zander@interlock.mckesson.com
Steve Grazzini:
  - grazz@pobox.com
Steve Hay:
  - SteveHay@planit.com
Steve Kelem:
  - steve.kelem@xilinx.com
Steve Nielsen:
  - spn@enteract.com
Steve Peters:
  - steve@fisharerojo.org
Steve Purkis:
  - Steve.Purkis@multimap.com
Steven Knight:
  - knight@theopera.baldmt.citilink.com
Steven N. Hirsch:
  - hirschs@stargate.btv.ibm.com
Steven Parkes:
  - parkes@sierravista.com
Steven Philip Schubiger:
  - steven@accognoscere.org
Steven Schubiger:
  - schubiger@cpan.org
Stian Seeberg:
  - sseeberg@nimsoft.no
Stéphane Payrard:
  - stef@mongueurs.net
Sven Verdoolaege:
  - skimo@breughel.ufsia.ac.be
SynaptiCAD, Inc.:
  - sales@syncad.com
Sébastien Aperghis-Tramoni:
  - sebastien@aperghis.net
Sérgio Durigan Júnior:
  - sergiodj@linux.vnet.ibm.com
Tassilo von Parseval:
  - tassilo.parseval@post.rwth-aachen.de
Tatsuhiko Miyagawa:
  - miyagawa@edge.co.jp
Ted Ashton:
  - ashted@southern.edu
Ted Law:
  - tedlaw@cibcwg.com
Tels:
  - nospam-abuse@bloodgate.com
The Doctor:
  - doctor@doctor.nl2k.ab.ca
Thomas Bowditch:
  - bowditch@inmet.com
Thomas Conté:
  - tom@fr.uu.net
Thomas Dorner:
  - Thomas.Dorner@start.de
Thomas Pfau:
  - pfau@nbpfaus.net
Thomas Wegner:
  - wegner_thomas@yahoo.com
Thorsten Glaser:
  - unknown
Tim Ayers:
  - tayers@bridge.com
Tim Bunce:
  - perlbug-followup@perl.org
  - Tim.Bunce@ig.co.uk
  - Tim.Bunce@pobox.com
Tim Conrow:
  - tim@spindrift.srl.caltech.edu
Tim Jenness:
  - t.jenness@jach.hawaii.edu
  - tjenness@cpan.org
Tim Sweetman:
  - tim@aldigital.co.uk
Tim Witham:
  - twitham@pcocd2.intel.com
Tkil:
  - tkil@reptile.scrye.com
Todd C. Miller:
  - Todd.Miller@courtesan.com
Todd Rinaldo:
  - perlbug-comment@perl.org
  - toddr@cpanel.net
Todd T. Fries:
  - todd@fries.int.mrleng.com
Todd Vierling:
  - tv@duh.org
Tom Brown:
  - thecap@peach.ece.utexas.edu
Tom Callaway:
  - unknown
Tom Christiansen:
  - tchrist@jhereg.perl.com
  - tchrist@mox.perl.com
  - tchrist@perl.com
Tom Horsley:
  - Tom.Horsley@mail.ccur.com
  - tom@amber.ssd.hcsc.com
Tom Hughes:
  - tom@compton.nu
Tom Hukins:
  - tom@eborcom.com
Tom Phoenix:
  - tomphoenix@unknown
  - rootbeer@teleport.com
Tom Spindler:
  - dogcow@isi.net
Tom Wyant:
  - unknown
Ton Hospel:
  - perl5-porters@ton.iguana.be
  - me-01@ton.iguana.be
  - perl-5.8.0@ton.iguana.be
Tony Bowden:
  - tony@kasei.com
Tony Cook:
  - tony@develop-help.com
Tony Sanders:
  - sanders@bsdi.com
Torsten Foertsch:
  - torsten.foertsch@gmx.net
Torsten Schoenfeld:
  - kaffeetisch@gmx.de
Trevor Blackwell:
  - tlb@viaweb.com
Tsutomu IKEGAMI:
  - t-ikegami@aist.go.jp
Tye McQueen:
  - tye@metronet.com
U-Adam-PC\Adam:
  - Adam@Adam-PC.(none)
Ulrich Pfeifer:
  - pfeifer@charly.informatik.uni-dortmund.de
  - pfeifer@wait.de
  - upf@de.uu.net
data-drift@so.uio.no:
  - data-drift@so.uio.no
Unknown:
  - unknown@unknown
Unknown Ricoh Contributor II:
  - maeda@src.ricoh.co.jp
Vadim Konovalov:
  - vkonovalov@lucent.com
Valeriy E. Ushakov:
  - uwe@ptc.spbu.ru
Ville Skyttä:
  - scop@cs132170.pp.htv.fi
Vincent Pit:
  - perl@profvince.com
  - vince@profvince.com
Vishal Bhatia:
  - vishal@deja.com
Vlad Harchev:
  - hvv@hippo.ru
W. Phillip Moore:
  - wpm@ms.com
W.BRISCOE@ponl.com:
  - W.BRISCOE@ponl.com
Walt Mankowski:
  - waltman@pobox.com
Warren Hyde:
  - whyde@pezz.sps.mot.com
Warren Jones:
  - wjones@tc.fluke.com
Wayne Scott:
  - wscott@ichips.intel.com
Wilfredo Sánchez:
  - wsanchez@mit.edu
William Mann:
  - wmann@avici.com
William Middleton:
  - wmiddlet@Adobe.COM
  - wmiddlet@adobe.com
William R Ward:
  - hermit@BayView.COM
Wilson P. Snyder II:
  - unknown@perl.org
Winfried König:
  - win@in.rhein-main.de
Wolfgang Laun:
  - Wolfgang.Laun@alcatel.at
Xavier Noria:
  - fxn@hashref.com
YAMASHINA Hio:
  - hio@ymir.co.jp
Yasuhiro Matsumoto:
  - mattn.jp@gmail.com
Yasushi Nakajima:
  - sey@jkc.co.jp
Yitzchak Scott-Thoennes:
  - sthoenna@efn.org
  - ysth@raven.shiftboard.com
Yuval Kogman:
  - nothingmuch@woobling.org
Yuval Kojman:
  - unknown
Yves Orton:
  - demerphq@camel.booking.com
  - demerphq@dromedary.booking.com
  - demerphq@gemini.(none)
  - demerphq@gmail.com
  - bugs-perl5@bugs6.perl.org
  - unknown
Zachary Miller:
  - zcmiller@simon.er.usgs.gov
Zefram:
  - unknown
  - zefram@fysh.org
Zsban Ambrus:
  - perlbug-followup@perl.org
  - unknown
abela@geneanet.org:
  - abela@geneanet.org
agrow@thegotonerd.com:
  - agrow@thegotonerd.com
alexander_bluhm@genua.de:
  - alexander_bluhm@genua.de
ammon@rhythm.com:
  - ammon@rhythm.com
anders@broadcom.com:
  - anders@broadcom.com
andrew deryabin:
  - djsf@technarchy.ru
andrew@sundale.net:
  - andrew@sundale.net
arbor@al37al08.telecel.pt:
  - arbor@al37al08.telecel.pt
author scotth@sgi.com 842220273 +0000:
  - author scotth@sgi.com 842220273 +0000
bah@longitude.com:
  - bah@longitude.com
bart@cg681574-a.adubn1.nj.home.com:
  - bart@cg681574-a.adubn1.nj.home.com
bbucklan@jpl-devvax.jpl.nasa.gov:
  - bbucklan@jpl-devvax.jpl.nasa.gov
beau@beaucox.com:
  - beau@beaucox.com
belg4mit:
  - belg4mit@mit.edu
ben@linuxgazette.net:
  - ben@linuxgazette.net
bharanee rathna:
  - unknown
bilbo@ua.fm:
  - bilbo@ua.fm
blino@mandriva.com:
  - blino@mandriva.com
bob@starlabs.net:
  - bob@starlabs.net
bonefish@cs.tu-berlin.de:
  - bonefish@cs.tu-berlin.de
brian d foy:
  - bdfoy@cpan.org
  - brian.d.foy@gmail.com
  - unknown
bstrand@switchmanagement.com:
  - bstrand@switchmanagement.com
chocolateboy:
  - chocolateboy@chocolatey.com
chris@broadband.att.com:
  - chris@broadband.att.com
chromatic:
  - chromatic@wgz.org
coral:
  - coral@moonlight.crystalflame.net
  - coral@eekeek.org
cygwin.com:
  - cygwin@cygwin.com
dLux:
  - dlux@spam.sch.bme.hu
daniel@biz.bitpusher.com:
  - daniel@biz.bitpusher.com
david@dhaller.de:
  - david@dhaller.de
deekoo:
  - deekoo@tentacle.net
dformosa@dformosa.zeta.org.au:
  - dformosa@dformosa.zeta.org.au
dgay@acm.org:
  - dgay@acm.org
erik@cs.uni-jena.de:
  - erik@cs.uni-jena.de
eserte@vran.herceg.de:
  - eserte@vran.herceg.de
fawaka@gmail.com:
  - perlbug-followup@perl.org
glasser@tang-eleven-seventy-nine.mit.edu:
  - glasser@tang-eleven-seventy-nine.mit.edu
gml4410@ggr.co.uk:
  - gml4410@ggr.co.uk
gomar@md.media-web.de:
  - gomar@md.media-web.de
grommel@sears.com:
  - grommel@sears.com
ian@dial.pipex.com:
  - ian@dial.pipex.com
ikegami:
  - eric@fmdev10.(none)
ilmari@vesla.ilmari.org:
  - ilmari@vesla.ilmari.org
ilya@juil.nonet:
  - ilya@juil.nonet
insecure:
  - insecure@mail.od.ua
jason stewart:
  - jasons@sandy-home.arc.unm.edu
jdhedden@1979.usna.com:
  - jdhedden@1979.usna.com
jms@mathras.comcast.net:
  - jms@mathras.comcast.net
johnh@isi.edu:
  - johnh@isi.edu
josh:
  - twists@gmail.com
js@ddre.dk:
  - js@ddre.dk
juna:
  - ggl.20.jj...@spamgourmet.com
kaminsky@math.huji.ac.il:
  - kaminsky@math.huji.ac.il
kan@dcit.cz:
  - kan@dcit.cz
karl williamson:
  - public@khwilliamson.com
kevin brintnall:
  - kbrint@rufus.net
kipp@shonanblue.ne.jp:
  - kipp@shonanblue.ne.jp
kmx:
  - kmx@volny.cz
knew-p5p@pimb.org:
  - knew-p5p@pimb.org
kvr@centrum.cz:
  - kvr@centrum.cz
lane@duphy4.physics.drexel.edu:
  - lane@duphy4.physics.drexel.edu
lemkemch@t-online.de:
  - lemkemch@t-online.de
mats@sm5sxl.net:
  - mats@sm5sxl.net
matthew green:
  - mrg@splode.eterna.com.au
mauzo@csv.warwick.ac.uk:
  - mauzo@.(none)
  - mauzo@csv.warwick.ac.uk
merijnb@ms.com:
  - merijnb@ms.com
mike@bill.iac.net:
  - mike@bill.iac.net
mike@exegenix.com:
  - mike@exegenix.com
ml1050:
  - ml1050@freemail.hu
mlelstv@serpens.de:
  - mlelstv@serpens.de
mls@suse.de:
  - mls@suse.de
nick@babyhippo.com:
  - nick@babyhippo.com
nperez:
  - nperez@cpan.org
oracle@pcr8.pcr.com:
  - oracle@pcr8.pcr.com
p.boven@sara.nl:
  - p.boven@sara.nl
padre@elte.hu:
  - padre@elte.hu
pancho@pancho.name:
  - pancho@pancho.name
parv:
  - parv@pair.com
paul:
  - paul@paul-desktop.(none)
perlbug-followup@perl.org:
  - perlbug-followup@perl.org
veggiechinese.net:
  - perlbug@veggiechinese.net
pm@capmon.dk:
  - pm@capmon.dk
pravus@cpan.org:
  - pravus@cpan.org
premchai21@yahoo.com:
  - premchai21@yahoo.com
pxm@nubz.org:
  - pxm@nubz.org
rabbit.us:
  - rabbit+bugs@rabbit.us
raf@tradingpost.com.au:
  - raf@tradingpost.com.au
root@chronos.fi.muni.cz:
  - root@chronos.fi.muni.cz
root@dixie.cscaper.com:
  - root@dixie.cscaper.com
root@dogberry.rutgers.edu:
  - root@dogberry.rutgers.edu
root@dubravka.in-berlin.de:
  - root@dubravka.in-berlin.de
root@jester.slaysys.com:
  - root@jester.slaysys.com
root@ak-75.mind.de:
  - root@ak-75.mind.de
root@devsys0.zenez.com:
  - root@devsys0.zenez.com
root@egg.karlov.mff.cuni.cz:
  - root@egg.karlov.mff.cuni.cz
scott@perlcode.org:
  - scott@perlcode.org
smoketst@hp46t243.cup.hp.com:
  - smoketst@hp46t243.cup.hp.com
root@peano.zk3.dec.com:
  - root@peano.zk3.dec.com
wolfgang.laun@chello.at:
  - wolfgang.laun@chello.at
yath-perlbug@yath.de:
  - yath-perlbug@yath.de
Ævar Arnfjörð Bjarmason:
  - avar@cpan.org
  - avarab@gmail.com
貞廣知行:
  - bqw10602@nifty.com
